## Numerical Operations on NumPy

In [1]:
import numpy as np

#### Element Wise addition and multiplication of arrays

In [5]:
a = np.array([1,2,3,4]) #create array
print(a+1) #elementwise operations

[2 3 4 5]


In [6]:
print(a**2)

[ 1  4  9 16]


In [7]:
b = np.ones(4)+1
print(a-b)

[-1.  0.  1.  2.]


In [9]:
print(a)
print(b)
print(a*b)

[1 2 3 4]
[ 2.  2.  2.  2.]
[ 2.  4.  6.  8.]


In [12]:
#Matrix Multiplication

c = np.diag([1,2,3,4])
print(c*c)
print("*****************")
print(c.dot(c)) #dot notation can also be used to multiply array

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
*****************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [15]:
#Element wise comparision

a = np.array([1,2,3,4])
b = np.array([1,2,4,3])
print(a==b)
print("***********")
print(a>b)
np.array_equal(a,b) #Element wise array comparision

[ True  True False False]
***********
[False False False  True]


False

### Logical Operators
and,or

In [19]:
a = np.array([1,0,0,1], dtype=bool)
b = np.array([1,1,0,0], dtype=bool)

print(np.logical_or(a,b))
print(np.logical_and(a,b))

[ True  True False  True]
[ True False False False]


### Trancedental operators 
sin,log,exp

In [22]:
a = np.arange(5)
print(np.sin(a))
print(np.log(a))
print(np.exp(a)) # e^x

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
[       -inf  0.          0.69314718  1.09861229  1.38629436]
[  1.           2.71828183   7.3890561   20.08553692  54.59815003]


/home/kdpingali/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in log
  This is separate from the ipykernel package so we can avoid doing imports until


### Shape Mismatch

In [23]:
a = np.arange(4)
a + np.array([1,2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

### Basic Reductions
#### Computing Sums

In [24]:
x = np.array([1,2,3,4])
np.sum(x)

10

In [26]:
#sum by rows and columns
x = np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [27]:
x.sum(axis=0) #columns first dimension i.e column wise sum

array([3, 3])

In [28]:
x.sum(axis=1) #rows first dimension i.e row wise sum

array([2, 4])

### Other reductions

In [32]:
x = np.array([1,2,3,4])
print(x.min()) #minimum element
print(x.argmin()) #index of minimum element

1
0


In [30]:
x = np.array([1,2,3,4])
x.max()

4

### Logical Operations

In [33]:
np.any([True, False, True])

True

In [34]:
np.all([True, True, False]) # all elements have to be true

False

In [35]:
a = np.zeros((50,50))
np.any(a != 0)

False

In [36]:
np.all(a==a)

True

In [37]:
np.all(a==3)

False

In [38]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([1,2,3,4])
((a <= b) & (b > c)).all() # returns true only if all elements of a,b,c satisfies the condition

True

### Statistics

In [39]:
x = np.array([1,2,3])
x.mean()


2.0

In [41]:
np.median(x)

2.0

In [42]:
y = np.array([[1,2],[3,4]])
np.median(y,axis=1) #median row wise since axis=1

array([ 1.5,  3.5])

In [43]:
x.std() #standard deviation

0.81649658092772603

### Example
Data in populations.txt describes the population of rabbits and hares

In [44]:
# Load data into numpy array object
data = np.loadtxt('populations.txt')

In [45]:
data

array([[  1900.,  30000.,   4000.,  48300.],
       [  1901.,  47200.,   6100.,  48200.],
       [  1902.,  70200.,   9800.,  41500.],
       [  1903.,  77400.,  35200.,  38200.],
       [  1904.,  36300.,  59400.,  40600.],
       [  1905.,  20600.,  41700.,  39800.],
       [  1906.,  18100.,  19000.,  38600.],
       [  1907.,  21400.,  13000.,  42300.],
       [  1908.,  22000.,   8300.,  44500.],
       [  1909.,  25400.,   9100.,  42100.],
       [  1910.,  27100.,   7400.,  46000.],
       [  1911.,  40300.,   8000.,  46800.],
       [  1912.,  57000.,  12300.,  43800.],
       [  1913.,  76600.,  19500.,  40900.],
       [  1914.,  52300.,  45700.,  39400.],
       [  1915.,  19500.,  51100.,  39000.],
       [  1916.,  11200.,  29700.,  36700.],
       [  1917.,   7600.,  15800.,  41800.],
       [  1918.,  14600.,   9700.,  43300.],
       [  1919.,  16200.,  10100.,  41300.],
       [  1920.,  24700.,   8600.,  47300.]])