In [2]:
import numpy as np

a = np.array([0,1,2,3]) #takes a list as input and represents it internally as a numpy array
print(a)

print(np.arange(10)) #creates a numpy array of first 10 integers

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


Numpy is a memory efficient container that provides fast numerical computations

In [3]:
L = range(1000) #python lists
%timeit [i**2 for i in L] #squaring each number in the list

355 µs ± 19.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


###### timeit: measures the time taken per iteration

In [4]:
a = np.arange(1000) #numpy array
%timeit a**2

2.45 µs ± 78 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Observe the difference between time take to compute square of a number using lists and numpy array.
Computation for numpy array elements is way faster than lists.
This is what makes numpy memory efficient and extremely fast numerical computation

###Creating numpy array


In [5]:
#1 D

ary = np.array([0,1,2,3])
ary

array([0, 1, 2, 3])

In [6]:
#print dimensions
ary.ndim

1

In [7]:
#print shape
ary.shape

(4,)

In [8]:
#len of array
len(ary)

4

In [9]:
#2 D, input as list of lists
ary = np.array([[0,1,2,3],[4,5,6,7]])
print(ary)
print ("dimensions: ") 
print (ary.ndim)
print ("shape: ") 
print (ary.shape)

[[0 1 2 3]
 [4 5 6 7]]
dimensions: 
2
shape: 
(2, 4)


In [10]:
#3D, List of list of lists

ary = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(ary)
print("dimensions: ")
print(ary.ndim)
print("shape: ")
print(ary.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
dimensions: 
3
shape: 
(2, 2, 2)


In [13]:
#create numpy array
a = np.arange(1,10,2) #(start,end(exclusive),stepsize)
print(a)
a

[1 3 5 7 9]


array([1, 3, 5, 7, 9])

In [16]:
#create numpy array with linear space using linspace
a = np.linspace(0,1,6) #(start,end,number of points)its like dividing a line into 6 equal points
print(a)

b = np.linspace(0,6,6)
print(b)


[ 0.   0.2  0.4  0.6  0.8  1. ]
[ 0.   1.2  2.4  3.6  4.8  6. ]


In [24]:
#common array
a = np.ones((2,2)) #(here (2,2) is a tuple)
print(a)
b = np.zeros((4,4))
print(b)

[[ 1.  1.]
 [ 1.  1.]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [27]:
#creating identity matrix where diagonaal elements are 1 and all other elements are 0
a = np.eye(3,3)
a

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [28]:
#construct a diagonal array
a = np.diag([1,2,3,4]) #(here ([1,2,3,4]) is a list)
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [29]:
#Extract only diagonal elements
np.diag(a) #returns only diagonal elements as an np array

array([1, 2, 3, 4])

In [30]:
#create array using random

a = np.random.rand(4) #returns an array of 4 random numbers, these random numbers are uniform random variable, there are other radom number gaussian random variables
a

array([ 0.30936445,  0.05268418,  0.16913095,  0.91204385])

In [35]:
#datatypes

a = np.arange(10)
print(a)
a.dtype

[0 1 2 3 4 5 6 7 8 9]


dtype('int64')

In [34]:
a = np.arange(10,dtype=float)
print(a)
a.dtype

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


dtype('float64')

In [37]:
#complex datatype: complex numpy array

a = np.array([1+2j,2+4j])
a.dtype

dtype('complex128')

In [38]:
#boolean datatype: boolean numpy array

a = np.array([True, False])
a.dtype

dtype('bool')

In [42]:
#string 
s = np.array(['hi', 'hello', 'wher'])
s.dtype

dtype('<U5')

Each builtin type has a character code that uniquely identifies it
doc.scipy.org/doc/numpy-1.10.1/user/basics.types.html

In [43]:
#Indexing and slicing
#Indexing an np array is similar to c/c++ indexing

#slicing
a = np.arange(10)
print(a)

a[1:8:2] #(start index,end index(excluding),step)

[0 1 2 3 4 5 6 7 8 9]


array([1, 3, 5, 7])

In [46]:
#combining slicing and assignment
a[5:] = 10 #(make all the elements in a from index 5 to end to value=10)
print(a)

[ 0  1  2  3  4 10 10 10 10 10]


In [47]:
b = np.arange(5)
a[5:] = b[::-1] #(default=start_index:default=end_index:step -1=from the end i.e reverse order)
print(a)

[0 1 2 3 4 4 3 2 1 0]


In [ ]:
#Copies and views
