In [8]:
import numpy as np

a = np.array([0,1,2,3]) #takes a list as input and represents it internally as a numpy array
print(a)

print(np.arange(10)) #creates a numpy array of first 10 integers

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


Numpy is a memory efficient container that provides fast numerical computations

In [9]:
L = range(1000) #python lists
%timeit [i**2 for i in L] #squaring each number in the list

324 µs ± 8.79 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


###### timeit: measures the time taken per iteration

In [10]:
a = np.arange(1000) #numpy array
%timeit a**2

2.31 µs ± 111 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Observe the difference between time take to compute square of a number using lists and numpy array.
Computation for numpy array elements is way faster than lists.
This is what makes numpy memory efficient and extremely fast numerical computation

###Creating numpy array


In [11]:
#1 D

ary = np.array([0,1,2,3])
ary

array([0, 1, 2, 3])

In [12]:
#print dimensions
ary.ndim

1

In [13]:
#print shape
ary.shape

(4,)

In [16]:
#len of array
len(ary)

4

In [26]:
#2 D, input as list of lists
ary = np.array([[0,1,2,3],[4,5,6,7]])
print(ary)
print ("dimensions: ") 
print (ary.ndim)
print ("shape: ") 
print (ary.shape)

[[0 1 2 3]
 [4 5 6 7]]
dimensions: 
2
shape: 
(2, 4)


In [31]:
#3D, List of list of lists

ary = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(ary)
print("dimensions: ")
print(ary.ndim)
print("shape: ")
print(ary.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
dimensions: 
3
shape: 
(2, 2, 2)
