In [2]:
import numpy as np

a = np.array([0,1,2,3]) #takes a list as input and represents it internally as a numpy array
print(a)

print(np.arange(10)) #creates a numpy array of first 10 integers

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


Numpy is a memory efficient container that provides fast numerical computations

In [3]:
L = range(1000) #python lists
%timeit [i**2 for i in L] #squaring each number in the list

351 µs ± 9.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


###### timeit: measures the time taken per iteration

In [4]:
a = np.arange(1000) #numpy array
%timeit a**2

2.37 µs ± 116 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Observe the difference between time take to compute square of a number using lists and numpy array.
Computation for numpy array elements is way faster than lists.
This is what makes numpy memory efficient and extremely fast numerical computation

###Creating numpy array


In [5]:
#1 D

ary = np.array([0,1,2,3])
ary

array([0, 1, 2, 3])

In [6]:
#print dimensions
ary.ndim

1

In [7]:
#print shape
ary.shape

(4,)

In [8]:
#len of array
len(ary)

4

In [9]:
#2 D, input as list of lists
ary = np.array([[0,1,2,3],[4,5,6,7]])
print(ary)
print ("dimensions: ") 
print (ary.ndim)
print ("shape: ") 
print (ary.shape)

[[0 1 2 3]
 [4 5 6 7]]
dimensions: 
2
shape: 
(2, 4)


In [10]:
#3D, List of list of lists

ary = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(ary)
print("dimensions: ")
print(ary.ndim)
print("shape: ")
print(ary.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
dimensions: 
3
shape: 
(2, 2, 2)


In [11]:
#create numpy array
a = np.arange(1,10,2) #(start,end(exclusive),stepsize)
print(a)
a

[1 3 5 7 9]


array([1, 3, 5, 7, 9])

In [12]:
#create numpy array with linear space using linspace
a = np.linspace(0,1,6) #(start,end,number of points)its like dividing a line into 6 equal points
print(a)

b = np.linspace(0,6,6)
print(b)


[ 0.   0.2  0.4  0.6  0.8  1. ]
[ 0.   1.2  2.4  3.6  4.8  6. ]


In [13]:
#common array
a = np.ones((2,2)) #(here (2,2) is a tuple)
print(a)
b = np.zeros((4,4))
print(b)

[[ 1.  1.]
 [ 1.  1.]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [14]:
#creating identity matrix where diagonaal elements are 1 and all other elements are 0
a = np.eye(3,3)
a

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [15]:
#construct a diagonal array
a = np.diag([1,2,3,4]) #(here ([1,2,3,4]) is a list)
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [16]:
#Extract only diagonal elements
np.diag(a) #returns only diagonal elements as an np array

array([1, 2, 3, 4])

In [17]:
#create array using random

a = np.random.rand(4) #returns an array of 4 random numbers, these random numbers are uniform random variable, there are other radom number gaussian random variables
a

array([ 0.53904533,  0.96904885,  0.22421251,  0.94773952])

### Numpy datatypes

In [18]:
#datatypes

a = np.arange(10)
print(a)
a.dtype

[0 1 2 3 4 5 6 7 8 9]


dtype('int64')

In [19]:
a = np.arange(10,dtype=float)
print(a)
a.dtype

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


dtype('float64')

In [20]:
#complex datatype: complex numpy array

a = np.array([1+2j,2+4j])
a.dtype

dtype('complex128')

In [21]:
#boolean datatype: boolean numpy array

a = np.array([True, False])
a.dtype

dtype('bool')

In [22]:
#string 
s = np.array(['hi', 'hello', 'wher'])
s.dtype

dtype('<U5')

### Numpy indexing and slicing

Each builtin type has a character code that uniquely identifies it
doc.scipy.org/doc/numpy-1.10.1/user/basics.types.html

In [23]:
#Indexing and slicing
#Indexing an np array is similar to c/c++ indexing

#slicing
a = np.arange(10)
print(a)

a[1:8:2] #(start index,end index(excluding),step)

[0 1 2 3 4 5 6 7 8 9]


array([1, 3, 5, 7])

In [24]:
#combining slicing and assignment
a[5:] = 10 #(make all the elements in a from index 5 to end to value=10)
print(a)

[ 0  1  2  3  4 10 10 10 10 10]


In [25]:
b = np.arange(5)
a[5:] = b[::-1] #(default=start_index:default=end_index:step -1=from the end i.e reverse order)
print(a)

[0 1 2 3 4 4 3 2 1 0]


In [26]:
#Copies and views
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [27]:
b = a[::2]
print(b)

[0 2 4 6 8]


In [29]:
np.shares_memory(a,b)

True

In [32]:
b[0] = 10
print(b)
print(a)
#you can observe that a and b are sharing same space in memory, change by either a or b will effect both a and b

[10  2  4  6  8]
[10  1  2  3  4  5  6  7  8  9]


In [36]:
#Force copy to avoid sharing

a = np.arange(10)
c = a[::2].copy()
print(c)
np.shares_memory(a,c) #with this call you can check whether a and c are sharing memory

[0 2 4 6 8]


False

### Fancy Indexing
Numpy arrays can be indexed with slices, but also with boolean or integer arrays(masks). This method is called fancy indexing. It creates copies not views.
### Using Boolean Mask

In [39]:
a = np.random.randint(0,20,15)
print(a)
mask = (a%2 == 0)
extract_from_a = a[mask]
print(extract_from_a)

[17 13  5  3  2  1 17  1 18 19 10  2 15 18  8]
[ 2 18 10  2 18  8]


In [40]:
#assigning new values using mask
a[mask] = -1 #all values that validate to true on mask will be set to -1
print(a)

[17 13  5  3 -1  1 17  1 -1 19 -1 -1 15 -1 -1]


In [42]:
#indexing with an array of integers
a = np.arange(0,100,10)
print(a)

[ 0 10 20 30 40 50 60 70 80 90]


In [44]:
print(a[[2,4,2,3]]) #creating new array based on indices


[20 40 20 30]


In [45]:
a[[2,3]] = -1 #assigning new values based on indices
print(a)

[ 0 10 -1 -1 40 50 60 70 80 90]
